server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-vehicles
          uri: lb://ms-vehicles:8091
          predicates:
            - Path=/api/v1/vehicles/**
        - id: ms-repairList
          uri: lb://ms-repairList:8092
          predicates:
            - Path=/api/v1/repairList/**
        - id: ms-repairVehicles
          uri: lb://ms-repairVehicles:8093
          predicates:
            - Path=/api/v1/generateRepairs/**